### ISSUE TITLE
NVIDIA_dynexsolve_windows2.1.0f.7z can`t work

### ISSUE THREAD

**Issue by jiuyaopinyin** [dynexcoin/DynexSolve#2]
release [NVIDIA_dynexsolve_windows2.1.0f.7z](https://github.com/dynexcoin/Dynex/releases/download/Dynex_windows_2.1.0f/NVIDIA_dynexsolve_windows2.1.0f.7z)

Automatically exit when i open it

**Comment by xingxing1218** [comment]
低配置电脑可以运行吗？

**Comment by oseart55** [comment]
> release [NVIDIA_dynexsolve_windows2.1.0f.7z](https://github.com/dynexcoin/Dynex/releases/download/Dynex_windows_2.1.0f/NVIDIA_dynexsolve_windows2.1.0f.7z)
> 
> Automatically exit when i open it

@jiuyaopinyin You would need to provide more information on what the error is. I suspect the issue is you are trying to run DynexSolveVS.exe by itself. 
You will need to create a ".bat" file with the following line:
`dynexsolvevs.exe -mining-address YOURWALLET -daemon-host HOST -no-cpu -multi-gpu -stratum-url STRATUMURL -stratum-port STRATUMPORT -stratum-password YOURWORKER`

Otherwise, if that is not the issue, add `PAUSE` to the end of your ".bat" and you should be able to copy the error that it produces and get more specific help. 
![image_2022-12-04_134729994](https://user-images.githubusercontent.com/35896223/205517348-8752a05b-db3e-47b5-a5da-2e826da28ef7.png)
(as an example)
